import { resolve } from "node:path";
import { createApprovalQueue, renderApprovalQueue, type ApprovalQueue, type ApprovalRequest } from "./approval.ts";
import { createTraceRecorder, renderTraceTimeline } from "./audit.ts";
import { createJobStore, renderJobHistory, type CapabilityJob, type JobStore } from "./jobs.ts";
import { ingestPlainTextFile } from "./knowledge/ingest.ts";
import { createKnowledgeStore, renderKnowledgeSummary, type KnowledgeStore } from "./knowledge/store.ts";
import { createMcpClientManager, renderToolCatalog, type McpClientManager, type ToolDescriptor } from "./mcp-client.ts";
import { createModelRequest, renderModelRequestForAudit, type ModelAdapter } from "./model-adapter.ts";
import { createMockModelAdapter } from "./models/mock-model.ts";
import { createPolicyEngine } from "./policy.ts";
import { runTeamWorkflow } from "./team-runner.ts";
import type { PolicyEngine, TeamRunResult, ToolAction, TraceRecorder } from "./types.ts";

export type P1Context = {
  runId: string;
  trace: TraceRecorder;
  policy: PolicyEngine;
  approvals: ApprovalQueue;
  jobs: JobStore;
  knowledge: KnowledgeStore;
  mcp: McpClientManager;
  model: ModelAdapter;
};

export type P1RunOptions = {
  knowledgeFixturePath?: string;
  model?: ModelAdapter;
};

export type P1RunResult = {
  job: CapabilityJob;
  modelProposal: unknown;
  knowledgeSummary: string;
  toolCatalog: string;
  pendingApprovals: ApprovalRequest[];
  p0Result: TeamRunResult;
  traceTimeline: string;
  summary: string;
};

export async function runP1Workflow(userRequest: string, options: P1RunOptions = {}): Promise<P1RunResult> {
  const context = prepareP1Context({ model: options.model });
  const job = context.jobs.createJob("Hypothesis Analysis", { userRequest });
  context.jobs.updateJobStatus(job.jobId, "running", "P1 workflow started.");

  const modelRequest = createModelRequest({
    role: "planner",
    prompt: `Plan a controlled WARDEN workflow for: ${userRequest}`,
    context: { userRequest },
    responseFormat: "json"
  });
  context.trace.record({
    phase: "agent_output",
    actor: "system",
    summary: renderModelRequestForAudit(modelRequest),
    payload: modelRequest
  });
  const modelResponse = await context.model.generate(modelRequest);
  context.trace.record({
    phase: "agent_output",
    actor: "system",
    summary: `Model proposal generated by ${modelResponse.model}.`,
    payload: modelResponse
  });

  const units = runKnowledgeIngestion(context, options);
  context.jobs.appendJobHistory(job.jobId, {
    status: "running",
    summary: `Ingested ${units.length} knowledge units.`
  });

  registerP1LocalTools(context);
  const toolCatalog = renderToolCatalog(context.mcp.discoverTools());
  const pendingApproval = simulateExternalApprovalGate(context, job.jobId);

  const p0Invocation = await context.mcp.invokeTool<TeamRunResult>(
    {
      id: "p1-run-p0-team",
      tool: "run_warden_team",
      input: { userRequest }
    },
    {
      runId: context.runId,
      role: "supervisor",
      trace: context.trace,
      policy: context.policy,
      approvalQueue: context.approvals
    }
  );

  if (p0Invocation.status !== "succeeded" || !p0Invocation.output) {
    context.jobs.updateJobStatus(job.jobId, "failed", "P0 team execution failed inside P1 runner.");
    throw new Error("P1 failed: P0 team did not complete.");
  }

  context.jobs.updateJobStatus(job.jobId, "succeeded", "P1 workflow completed with P0 team result.", p0Invocation.output.run.id);

  const pendingApprovals = context.approvals.listPending(context.runId);
  const result: P1RunResult = {
    job,
    modelProposal: modelResponse.output,
    knowledgeSummary: renderKnowledgeSummary(context.knowledge.listKnowledgeUnits()),
    toolCatalog,
    pendingApprovals,
    p0Result: p0Invocation.output,
    traceTimeline: renderTraceTimeline(context.trace.getEvents()),
    summary: ""
  };
  result.summary = renderP1Summary(result, pendingApproval?.id);
  return result;
}

export function prepareP1Context(options: { model?: ModelAdapter } = {}): P1Context {
  const runId = `p1_${Date.now().toString(36)}`;
  return {
    runId,
    trace: createTraceRecorder(runId),
    policy: createPolicyEngine(),
    approvals: createApprovalQueue(),
    jobs: createJobStore(),
    knowledge: createKnowledgeStore(),
    mcp: createMcpClientManager({
      allowlist: {
        include: ["run_warden_team", "external_osint_fetch"],
        exclude: []
      }
    }),
    model: options.model ?? createMockModelAdapter()
  };
}

export function runKnowledgeIngestion(context: P1Context, options: P1RunOptions = {}) {
  const fixturePath = options.knowledgeFixturePath ?? resolve(process.cwd(), "fixtures/knowledge/supply-chain-notes.txt");
  const units = ingestPlainTextFile(fixturePath, {
    tags: ["supply-chain", "p1-fixture"]
  });
  context.knowledge.addKnowledgeUnits(units);
  context.trace.record({
    phase: "agent_output",
    actor: "system",
    summary: `Knowledge ingestion created ${units.length} units.`,
    payload: units
  });
  return units;
}

export function registerP1LocalTools(context: P1Context): ToolDescriptor[] {
  const runTeamDescriptor: ToolDescriptor = {
    name: "run_warden_team",
    server: "warden-local",
    capability: "Hypothesis Analysis",
    risk: "WRITE",
    description: "Runs the P0 WARDEN specialist team through a local capability wrapper."
  };
  const externalDescriptor: ToolDescriptor = {
    name: "external_osint_fetch",
    server: "external",
    capability: "RFI Watch",
    risk: "EXTERNAL",
    description: "Placeholder external OSINT fetch. Must require approval."
  };

  context.mcp.registerLocalTool<{ userRequest: string }, TeamRunResult>(runTeamDescriptor, (input) =>
    runTeamWorkflow(input.userRequest)
  );
  context.mcp.registerLocalTool(externalDescriptor, () => ({ blocked: true }));
  return [runTeamDescriptor, externalDescriptor];
}

export function simulateExternalApprovalGate(context: P1Context, jobId: string): ApprovalRequest | undefined {
  const action: ToolAction = {
    name: "external_osint_fetch",
    capability: "RFI Watch",
    server: "external",
    risk: "EXTERNAL",
    input: { query: "supply chain import anomaly public sources" }
  };
  const decision = context.policy.evaluate(action, { runId: context.runId, role: "supervisor" });
  context.trace.record({
    phase: "policy_decision",
    actor: "policy",
    ref: action.name,
    summary: `${decision.decision} ${decision.risk} for ${action.name}: ${decision.reason}`,
    payload: decision
  });

  if (decision.decision !== "require_approval") {
    return undefined;
  }

  const request = context.approvals.submit({
    runId: context.runId,
    action,
    decision,
    requestedBy: "supervisor",
    reason: decision.reason
  });
  context.jobs.updateJobStatus(jobId, "waiting_approval", "External OSINT fetch is pending approval.", request.id);
  context.jobs.updateJobStatus(jobId, "running", "Continuing offline deterministic analysis while external action remains pending.");
  context.trace.record({
    phase: "policy_decision",
    actor: "policy",
    ref: action.name,
    summary: `approval pending for ${action.name}`,
    payload: request
  });
  return request;
}

export function renderP1Summary(result: P1RunResult, highlightedApprovalId?: string): string {
  return [
    "WARDEN P1 Demo",
    "==============",
    `Job: ${result.job.jobId}`,
    `Status: ${result.job.status}`,
    "",
    "Job History",
    "-----------",
    renderJobHistory(result.job),
    "",
    "Tool Catalog",
    "------------",
    result.toolCatalog,
    "",
    "Knowledge Summary",
    "-----------------",
    result.knowledgeSummary,
    "",
    "Approval Queue",
    "--------------",
    result.pendingApprovals.length > 0
      ? renderApprovalQueue({ ...stubQueue(result.pendingApprovals) })
      : "No pending approvals.",
    highlightedApprovalId ? `\nHighlighted approval: ${highlightedApprovalId}` : "",
    "",
    "P0 Team Result",
    "--------------",
    `Run: ${result.p0Result.run.id}`,
    `Status: ${result.p0Result.run.status}`,
    `Survivors: ${result.p0Result.outputs.ach?.survivors.join(", ") ?? "n/a"}`,
    "",
    "P1 Trace",
    "--------",
    result.traceTimeline
  ].join("\n");
}

function stubQueue(items: ApprovalRequest[]) {
  return {
    listPending: () => items,
    submit: () => {
      throw new Error("summary queue is read-only");
    },
    approve: () => {
      throw new Error("summary queue is read-only");
    },
    deny: () => {
      throw new Error("summary queue is read-only");
    },
    get: (id: string) => items.find((item) => item.id === id),
    listAll: () => items
  };
}
